### ISSUE TITLE
Prefabs should hold soft references to assets

### ISSUE THREAD

**Issue by coderespawn** [coderespawn/prefabricator-ue4#11]
Prefabs save the data as exported text.  This doesn't make them show up in reference viewer and the editor cannot create redirectors due to it

**Comment by melMass** [comment]
@coderespawn Thanks for this great plugin, are you planning on adding reference support ? This is a must have to integrate it in a larger workflow

**Comment by coderespawn** [comment]
This has been fixed in the latest release (1.2.0)
