### ISSUE TITLE
Prefabricator is totally broken

### ISSUE THREAD

**Issue by dkoding** [coderespawn/prefabricator-ue4#14]
After creating prefabs and prefab collections, after restarting editor every prefab collection is broken. When I drag new prefabs (nested prefab collections) into the editor window the prefabs are completely empty. Existing prefabs already in the level won't randomize anymore.

Try this:

In PrefabricatorAsset.cpp, line 99:

```
        if (PrefabAssetPtr.IsNull()) {
            PrefabAssetPtr = Prefabs.Last().PrefabAsset;
        }
    }
    if (!PrefabAssetPtr.IsNull()) {
        return PrefabAssetPtr.LoadSynchronous();
    }
    return nullptr;


```

**Comment by coderespawn** [comment]
@dkoding Thank you for the bug report. This has been fixed in the latest release
